### ISSUE TITLE
Add logger getter in components

### ISSUE THREAD

**Issue by jotadrilo** [bitnami/nami-core#28]
It would be nice if we can get the logger from the components.

Currently, all the logger methods (`info`, `warn`, etc) are delegated to the main component so the component itself is a logger.

However, all the properties from the logger and the logger itself cannot be retrieved (the component's logger is a private object inside the component: `_logger`) and pass trough functions or classes constructors.

**Comment by marcosbc** [comment]
We're going to close this issue, because we are currently working on archiving this repository.
